#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 640

#define BOARD_WIDTH 18
#define BOARD_HEIGHT 20
#define	BLOCK_COUNT (BOARD_WIDTH * BOARD_HEIGHT)

#define BLOCK_SIZE 30
#define BULLET_SIZE 2
#define BORDER 20

#define SLOW_TIMER 5000
#define BULLET_TICK_LENGTH 400
#define INITIAL_TICK_LENGTH 1000
#define MESSAGE_TICK_LENGTH 2000
#define WAVE_TICK_LENGTH 15000

#define SCREEN_FPS 30
#define SCREEN_TICK (1000/SCREEN_FPS)

#define UP 1
#define UPRIGHT 2
#define RIGHT 3
#define DOWNRIGHT 4
#define DOWN 5
#define DOWNLEFT 6
#define LEFT 7
#define UPLEFT 8

#define PADDLE_WIDTH 10
#define PADDLE_HEIGHT 60
#define BALL_SIZE 10